### ISSUE TITLE
Error on spacy.load()

### ISSUE THREAD

**Issue by alice17** [Neoanarika/MBTI#1]
I tried to load the model but it gives me this error:

> nlp = spacy.load(".\\model")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\spacy\__init__.py", line 15, in load
    return util.load_model(name, **overrides)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spacy\util.py", line 116, in load_model
    return load_model_from_path(Path(name), **overrides)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spacy\util.py", line 156, in load_model_from_path
    return nlp.from_disk(model_path)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spacy\language.py", line 653, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spacy\util.py", line 511, in from_disk
    reader(path / key)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spacy\language.py", line 649, in <lambda>
    deserializers[name] = lambda p, proc=proc: proc.from_disk(p, vocab=False)
  File "pipeline.pyx", line 247, in spacy.pipeline.Pipe.from_disk
  File "C:\ProgramData\Anaconda3\lib\site-packages\spacy\util.py", line 511, in from_disk
    reader(path / key)
  File "pipeline.pyx", line 240, in spacy.pipeline.Pipe.from_disk.load_model
  File "C:\ProgramData\Anaconda3\lib\site-packages\thinc\neural\_classes\model.py", line 352, in from_bytes
    copy_array(dest, param[b'value'])
  File "C:\ProgramData\Anaconda3\lib\site-packages\thinc\neural\util.py", line 48, in copy_array
    dst[:] = src
ValueError: could not broadcast input array from shape (64) into shape (64,1)

**Comment by kinoc** [comment]
I think the easiest thing to do is just retrain a new model using the code in the workbook. Spacy had a dependency problem with their serialization code, and the new spacy model loader can have problems loading older models.
